<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- jQuery 1.8.0-->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.8.0.js" type="text/javascript"></script>

<!-- Cargador del layout para el idioma, menu y migas -->
<script src="${staticsUrl}/aa17a/scripts/aa17aMovilidad/_layoutLoader.js" type="text/javascript"></script>
<script src="${staticsUrl}/aa17a/scripts/aa17aMovilidad/jquery.mobile-1.3.2.min.js" type="text/javascript"></script>